services:
    xyzzy-gpt-bot:
        build: .
        container_name: xyzzy-gpt-bot
        image: xyzzy-gpt-bot:latest
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - ./db:/db
        environment:
            - DATABASE_URL=sqlite:///db/data.db
