services:
    bot:
        build: ./bot
        container_name: bot
        image: xyzzy-gpt-bot:latest
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - ./bot/db:/db
        environment:
            - DATABASE_URL=sqlite://./bot/db/data.db
