services:
    bot:
        container_name: bot
        image: xyzzy-gpt-bot:latest
        restart: unless-stopped
        ports:
            - "8080:8080"
            - "5005:5005"
        volumes:
            - ./bot/db:/db
        environment:
            - DATABASE_URL=sqlite:///./db/data.db
        build:
            context: .
            dockerfile: ./bot/Dockerfile
